### ISSUE TITLE
[Indexing] Gem step does not work

### ISSUE THREAD

**Issue by aallahyar** [gaoyan07/LSAT#4]
Hello Yan,

It seems that I have a problem in the indexing step. The BWT index works fine. But the gem-indexer fails to run.

I collected a log file as well as list of files that are generated so far:

[Run_Log.txt](https://github.com/yangao07/LAMSA/files/723321/Run_Log.txt)
[List_of_Files.txt](https://github.com/yangao07/LAMSA/files/723319/Files.txt)

**Comment by yangao07** [comment]
Hi Amin,

Can you upload the "./REF_GNM-mm9_BMajor_Chr7_109933500-112066500.fasta.log" file?
Thank you.

Yan

**Comment by aallahyar** [comment]
Thank you for your response Yan. 
Please find attached the log file. To give you more details, below is what I see when running the indexer command:
```
bash$ <Lamsa path>/lamsa index ./REF_GNM-mm9_BMajor_Chr7_109933500-112066500.fasta
[bwt_index] Building bwt-index for genome...
[BWTIncCreate] textLength=4266000, availableWord=5419684
[bwt_gen] Finished constructing BWT in 5 iterations.
[bwt_index] Building done!
[lamsa_index] Executing gem-indexer ...

gem-indexer error. (./REF_GNM-mm9_BMajor_Chr7_109933500-112066500.fasta.log)
[lamsa_index] Indexing undone, gem-indexer exit abnormally.

```


[REF_GNM-mm9_BMajor_Chr7_109933500-112066500.fasta.log](https://github.com/yangao07/LAMSA/files/724870/REF_GNM-mm9_BMajor_Chr7_109933500-112066500.fasta.log.txt)

**Comment by yangao07** [comment]
It seems that the log file does not provide any useful information.
I suggest you try running the program with the absolute path instead of the relative path.
Tell me if it works or not.
I will try to fix the problem to make lamsa more friendly.

Yan

**Comment by yangao07** [comment]
Hi,
I just can not see the error happen on my server.
Please make sure that you have enough space on your disk

Actually I also want to know if you can run GEM normally independently (without lamsa).

Yan

**Comment by aallahyar** [comment]
Hello Yan,

I have more information regarding this issue.

1. I was able to run your script in another machine.
2. I think the problem has something to do with an illegal instruction in "gem-indexer_generate". I tried to remove redirections to get the output on terminal. If I run:

`<path>/LAMSA/lamsa index ./ref.fasta`

I see the following out:

```
[bwt_index] Building bwt-index for genome...
[BWTIncCreate] textLength=169464, availableWord=215784
[bwt_gen] Finished constructing BWT in 5 iterations.
[bwt_index] Building done!
[lamsa_index] Executing gem-indexer ... <path>/LAMSA/gem/gem-indexer -i ./ref.fasta -o ./ref.fasta #> /dev/null 2> /dev/null
Welcome to GEM-indexer build 1.423 (beta) - (2013/04/01 01:02:13 GMT)
 (c) 2008-2013 Paolo Ribeca <paolo.ribeca@gmail.com>
 (c) 2010-2013 Santiago Marco Sola <santiagomsola@gmail.com>
 (c) 2010-2013 Leonor Frias Moya <leonor.frias@gmail.com>
For the terms of use, run the program with the option --show-license.
************************************************************************
* WARNING: this is a beta version, provided for testing purposes only; *
*          check for updates at <http://gemlibrary.sourceforge.net>.   *
************************************************************************
Creating sequence and location files... done.
Computing DNA BWT (likely to take long)... done.
Generating index (likely to take long)...
/bin/sh: line 1: 19609 Illegal instruction     gem-indexer_generate --append -i ./ref.fasta.fmi_dna-cont -o ./ref.fasta.gem -s 32 --index_type fmi-dna -b ./ref.fasta.fmi_dna-bwt --mm-tmp-prefix "/tmp/mm_new-" >> ./ref.fasta.log 2>&1
Fatal error: exception Failure("Command 'echo "-------gem-indexer_generate" >> ./ref.fasta.log && gem-indexer_generate --append -i ./ref.fasta.fmi_dna-cont -o ./ref.fasta.gem -s 32 --index_type fmi-dna -b ./ref.fasta.fmi_dna-bwt --mm-tmp-prefix "/tmp/mm_new-" >> ./ref.fasta.log

gem-indexer error. (./ref.fasta.log)
```

Just like before, the log file is not really helpful. But I will add it anyway.

[ref.fasta.log.txt](https://github.com/yangao07/LAMSA/files/745250/ref.fasta.log.txt)

**Comment by yangao07** [comment]
Hi Amin,
For the "illegal instruction", I think this is because the complied GEM-indexer in not compatible with your machine.
I guess this is because your CPU type is too old.
Here is the Installation Instruction of GEM: http://algorithms.cnag.cat/wiki/Installation_instructions. 
You can try to download the old-cpu version of GEM via the link: https://sourceforge.net/projects/gemlibrary/files/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_2-20130406-045632.tbz2/download
Just decompress them in the "gem" directory.
Tell me if it works or not.

Yan

**Comment by aallahyar** [comment]
Hello Yan,

I tested the script in the old server (using different available versions of GEM library). I can tell that same error pops up everytime. Just for future reference, here is some information about this server:
```
bash$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 23
Model name:            Intel(R) Xeon(R) CPU           E5410  @ 2.33GHz
Stepping:              10
CPU MHz:               2333.000
BogoMIPS:              4655.03
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              6144K
NUMA node0 CPU(s):     0-7
```

On the other hand, I can confirm that **it does work in several new servers** that I tested. This is good enough for me.

Thank you for taking the time to respond to this issue. I will close the issue.

**Comment by yangao07** [comment]
> Hi Amin,
> For the "illegal instruction", I think this is because the complied GEM-indexer in not compatible with your machine.
> I guess this is because your CPU type is too old.
> Here is the Installation Instruction of GEM: http://algorithms.cnag.cat/wiki/Installation_instructions.
> You can try to download the old-cpu version of GEM via the link: https://sourceforge.net/projects/gemlibrary/files/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_2-20130406-045632.tbz2/download
> Just decompress them in the "gem" directory.
> Tell me if it works or not.
> 
> Yan

If it is related the "Illegal instruction" error of GEM, you may want to try different machine/server to see if it can work.
