### ISSUE TITLE
Is LAMSA suitable for short reads?

### ISSUE THREAD

**Issue by songtaogui** [gaoyan07/LSAT#5]
Hi,

Thank you for developing the wonderful aligner LAMSA.

I have learned that when dealing with long reads, LAMSA has a good ability to handle SVs. 

I have some short reads (150bp paired-end reads), and I was wondering that if LAMSA is suitable for short reads mapping and if it still performs good when handling SVs? 

Best wishes，

SongtaoGui

**Comment by yangao07** [comment]
Hi Songtao,

Thanks for your interest in LAMSA.
But unfortunately, LAMSA is not suitable for short read (neither paired nor single).
For short-read alignment and SV detection, I would recommend you to try bwa-mem or other aligners, along with SV detection tools like LUMPY.
You may find some other useful tools [here](https://omictools.com/structural-variant-detection-category).

Yan

**Comment by songtaogui** [comment]
Hi yan，

Sorry for the delayed response.

Thank you for your kindly reply, your suggestions are quite helpful and I will try bwa-mem instead.

Best wishes,

Songtao Gui
